### ISSUE TITLE
Not able to use the Setup.sh file

### ISSUE THREAD

**Issue by chander1988** [bgaldino/sm-quickstart#10]
Hi , I am not able to use the setup script , while running the script i am getting expecption .

\033[0;36minstanceUrl\033[0m:\033[0;33mhttps://enterprise-flow-6127.scratch.my.salesforce.com\033[0m
\033[0;32mCurrent myDomain: \033[0m
\033[0;36mmyDomain\033[0m:\033[0;33menterprise-flow-6127.scratch.my.salesforce.com\033[0m
\033[0;32mCurrent mySubDomain: \033[0m
\033[0;36mmySubDomain\033[0m:\033[0;33menterprise-flow-6127\033[0m

'C:\Program' is not recognized as an internal or external command,
operable program or batch file.
\033[0;32mEmail: \033[0m
\033[0;36m\033[0m
\033[0;32mSetting Default Org Settings\033[0m
\033[0;32mDeploying default org settings\033[0m
Deploying v57.0 metadata to test-qktyjfhwzfs4@example.com using the v57.0 SOAP API
Deploy ID: 0Af0100000lzSbWCAU
DEPLOY PROGRESS | ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░ | 0/6 Components
DEPLOY PROGRESS | █████████████████████████████████░░░░░░░ | 5/6 Components
DEPLOY PROGRESS | ████████████████████████████████████████ | 6/6 Components

=== Deployed Source

 FULL NAME              TYPE     PROJECT PATH
 ────────────────────── ──────── ─────────────────────────────────────────────────────────────────────────
 Commerce               Settings sm\sm-base\main\default\settings\Commerce.settings-meta.xml
 ExperienceBundle       Settings sm\sm-base\main\default\settings\ExperienceBundle.settings-meta.xml
 InvLatePymntRiskCalc   Settings sm\sm-base\main\default\settings\InvLatePymntRiskCalc.settings-meta.xml
 Order                  Settings sm\sm-base\main\default\settings\Order.settings-meta.xml
 Quote                  Settings sm\sm-base\main\default\settings\Quote.settings-meta.xml
 SubscriptionManagement Settings sm\sm-base\main\default\settings\SubscriptionManagement.settings-meta.xml
Deploy Succeeded.
Setting Org Settings Failed.

**Comment by bgaldino** [comment]
Hi - the scripts have been developed and tested on osx and will only work unmodified on a Unix-based operating system.

There are various options for executing on windows, such as via windows subsystem for linux or using a bash interpreter for powershell.  However modifications would most likely be needed to account for paths and line endings.  It has been confirmed to work on windows after making these modifications, but the details have not yet been documented.

We may create a documented process for windows version in the future, but no decision has been made on if and when this will happen.

**Comment by chander1988** [comment]
Thanks for the update

**Comment by bgaldino** [comment]
The script has been updated and confirmed to work on Windows via WSL2.
