### ISSUE TITLE
./setup.sh failing with JitPluginInstallError: Could not install @salesforce/plugin-community

### ISSUE THREAD

**Issue by gvpatel** [bgaldino/sm-quickstart#13]
Querying Data... done
paymentGatewayId:0b0Dp000000CppFIAS
Checking for existing Subscription Management Customer Account Portal Digital Experience
Querying Data... done
**Creating Subscription Management Customer Account Portal Digital Experience
    JitPluginInstallError: Could not install @salesforce/plugin-community
    Code: JitPluginInstallError**
Subscription Management Customer Community not yet created, waiting 10 seconds...
Querying Data... done
Subscription Management Customer Community not yet created, waiting 10 seconds...
Querying Data... done
Subscription Management Customer Community not yet created, waiting 10 seconds...
Querying Data... done

**Comment by bgaldino** [comment]
this issue may appear depending on which sfdx version is installed.  I checked in a fix to use the syntax for sfdx instead of sf, and it works in tests in both scratch and a new dev org.  You should always make sure sfdx is current by running 'sfdx update'.
