### ISSUE TITLE
Script requires WSL for Windows users and won't work with Terminal Emulator

### ISSUE THREAD

**Issue by mailalokagrawal** [bgaldino/sm-quickstart#4]
The script won't work with PowerShell or terminal emulators on Windows. I was able to make it work with WSL (Ubuntu) with a fresh install of SFDX within WSL. Using existing windows install of SFDX inside WSL will not work. I also had to change the shebang from #!/bin/sh to #!/bin/bash.
Start the script from WSL using the following command
 /bin/bash ./setup.sh

**Comment by bgaldino** [comment]
I'm not planning on creating or maintaining a windows version of the quickstart scripts, but thanks for posting a workaround in case others are using Windows environments.

**Comment by bgaldino** [comment]
script has been updated and confirmed to work with WSL2 on Windows.  We may consider making a powershell version at some point, but we're planning on support via git-bash as our next Windows compatibility enhancement.
