### ISSUE TITLE
Script can fail while importing contacts if the scratch org locale is not US

### ISSUE THREAD

**Issue by mailalokagrawal** [bgaldino/sm-quickstart#5]
The script can fail if the scratch org is created in a different locale (which is inherited from DevHub if not explicitly specified). I was able to work around this issue by setting the country explicitly to the US in the scratch org definition file.

**Comment by bgaldino** [comment]
Thanks - we're currently only testing with US locale and have added the country option to the def files and have explicitly set to "US"
