### ISSUE TITLE
plugin Community | getaddrinfo ENOTFOUND platform

### ISSUE THREAD

**Issue by dennisofcourse** [bgaldino/sm-quickstart#50]
When running the script I come across this issue..

error An unexpected error occurred: "http://platform-cli-registry.eng.sfdc.net:4880/@salesforce%2fplugin-community: getaddrinfo ENOTFOUND platform
Installing plugin community... failed
    JitPluginInstallError: Could not install @salesforce/plugin-community
    Code: JitPluginInstallError

---------------------------------------------------------
SFDX CLI Version: SF 2.0.2 darwin-arm64 node-v18.15.0
Node Version: 18.16.1 (LTS)
NPM Version: 9.5.1

No proxies or VPNs in place. Already tried reinstalling CLI / NPM, reauthorising Salesforce DevHub etc., nothing seems to solve the issue.

**Comment by snehaTrail2023** [comment]
Hi @bgaldino  we are facing same issue with new set up file available . 
![image](https://github.com/bgaldino/sm-quickstart/assets/142567349/792bc6f5-8e29-49e4-9158-ef09bc2887a2)

Can you please help us in resolving the issue

**Comment by dennisofcourse** [comment]
@snehaTrail2023 I was able to resolve the issue as follows.. install the plugins manually **before** running the script

`sf plugins install packaging`
`sf plugins install community`
`sf plugins install @salesforce/commerce`
